### PR TITLE
Bug 1979966: Update containers/storage to address incorrect overlay options being set on rhel7 nodes

### PR DESCRIPTION
**Pull request by nalind**
Bump github.com/containers/storage to have it correctly diagnose when globally-set options will cause problems for the overlay driver.  Bump github.com/containers/image to v5.16.1.  This is here mainly to keep us ahead of #274.

### CODE REVIEW

**Comment by gabemontero** [comment]
same situation with image-eco here and the python image as I noted in the 4.9 PR for this

**Comment by adambkaplan** [comment]
@nalind is this related to https://bugzilla.redhat.com/show_bug.cgi?id=1979966?

**Comment by nalind** [comment]
> @nalind is this related to https://bugzilla.redhat.com/show_bug.cgi?id=1979966?

Yes, though I'm hoping to not have to jump to a commit that isn't a tagged release unless we need to.

**Comment by adambkaplan** [comment]
/retitle Bug 1979966: Update containers/storage to address incorrect overlay options being set on rhel7 nodes

**Comment by adambkaplan** [comment]
/cc @jitendar-singh @prietyc123 

We need to test this PR with RHEL7 worker nodes. It isn't clear if this can be easily done pre-merge.

**Comment by gabemontero** [comment]
feel free to self approve @adambkaplan unless you'd rather @coreydaley do it for your PR

**Review by adambkaplan — COMMENTED** [review]
/approve

We will need to rely on QE to verify that it works on rhel7 nodes for now.
I will try to see if our CI infra can spin up a cluster with RHEL7 workers.

**Pull request merged**
