### PR TITLE
Bug 1817175: bump github.com/containers/buildah and dependencies

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Emulates #141 but for the OCP 4.4 branch.  Stealing from @nalind 's PR notes from there:

Bump github.com/containers/buildah to v1.14.2, github.com/containers/image/v5 to v5.2.1, github.com/containers/storage to v1.16.1, and their various dependencies, largely to pull in containers/buildah#2095.

Update for API changes in buildah:

    buildah.BuilderOptions no longer includes AddCapabilities and DropCapabilities slices, but now expects a unified Capabilities field which should be computed by passing those slices to github.com/containers/common/pkg/config.Default().Capabilities().
    imagebuildah.BuildOptions.TransientMounts is now a slice of string specifications for transient mounts rather than the structures we generate by parsing those specifications.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@nalind PTAL.  The one spot that I'm puzzled by is the lack of change for containers/common here.  It did not end up in go.mod after doing the go get for Buildah or after doing a go get directly for v0.4.2....

**Comment by nalind** [comment]
> @nalind PTAL. The one spot that I'm puzzled by is the lack of change for containers/common here. It did not end up in go.mod after doing the go get for Buildah or after doing a go get directly for v0.4.2....

I'm not super-worried about that, though I'm curious about the lack of an "indirect" reference, too.  The module shows up in `vendor/modules.txt`, and it's definitely in the patch.

**Comment by TomSweeneyRedHat** [comment]
Oh dang it @nalind.  I'd those in my original sandbox, but had to blow that away and restart and forgot to add them.  WIll do so now.

**Comment by TomSweeneyRedHat** [comment]
@nalind, I've added the changes to the two files now.  Fingers crossed for happier tests/bulids.  Thx for the help!

**Comment by adambkaplan** [comment]
@TomSweeneyRedHat @nalind do we need this backported to 4.4? Is this a blocker for teams to migrate their CI builds to 4.x clusters?

**Comment by nalind** [comment]
The bug ID we're referencing here has a dependent bug, and [one of its comments](https://bugzilla.redhat.com/show_bug.cgi?id=1810069#c4) suggested that we wanted to fix this for 4.4 once we had it sorted for 4.5/master.

**Comment by adambkaplan** [comment]
/retitle [release-4.4] Bug 1817175: bump github.com/containers/buildah and dependencies

**Comment by TomSweeneyRedHat** [comment]
@adambkaplan @nalind  Not sure about next steps for this especially given the robot's comment up a few?

**Comment by adambkaplan** [comment]
@TomSweeneyRedHat bug 1810069 is for the change that was needed in buildah. It's in the `Containers` component, though I'm not as familiar with how you are managing bugs for buildah. I'm dropping the dependency as the fix for buildah is already available.

Bug 181074 is for this identical fix, but in the master branch. We are not allowed to backport bugfixes without them being verified in `master` first.

/bugzilla refresh

**Comment by TomSweeneyRedHat** [comment]
@adambkaplan @nalind should I spin similar up for the 4.3 branch?

**Comment by adambkaplan** [comment]
@TomSweeneyRedHat is such a backport possible using the buildah 1.11.x codebase? My first take is that bumping the buildah version past a z-stream introduces additional risk that we can't take in a z-stream backport. This current PR is aiming for 4.4.0.

Given the severity in the BZ (urgent), we should try and backport to 4.3.z at minimum.

**Comment by rhatdan** [comment]
@adambkaplan Did buildah support http based builds at that time.  I remember we had to fix this at one point.

**Comment by adambkaplan** [comment]
> Did buildah support http based builds at that time. I remember we had to fix this at one point.

@rhatdan Can you please clarify what you mean by this? Are you referring to using a URL as the Dockerfile for `buildah bud`?

**Comment by rhatdan** [comment]
Yes, I thought this was something we fixed in a buildah release, where we did not always support http protocol for buildah bud

**Comment by TomSweeneyRedHat** [comment]
We had two URL changes in `buildah bud`

v1.11.6 (Dec 3, 2019)
bud COPY does not download URL - https://github.com/containers/buildah/pull/1977

v1.4  (Oct 2, 2018)
Fix --layers ADD from url issue - https://github.com/containers/buildah/pull/947

I think the 1.11.6 one is the one you're remembering Dan.  I'm not sure how that version lines up with OCP 4.3.z though.  I'll poke  around later today in the code, but if anyone else has more knowledge, please let me know.

**Comment by sdodson** [comment]
/retitle Bug 1817175: bump github.com/containers/buildah and dependencies

**Pull request merged**
