### PR TITLE
Bug 1964327: bump github.com/containers/buildah to v1.22.3

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by nalind** [comment]
Looks we've got a test failure at https://github.com/openshift/origin/blob/134ea3ec14162a3fdd98523bf22dcbec672521f1/test/extended/builds/multistage.go#L84 caused by https://github.com/containers/buildah/pull/3265, which changed the logged output for the first FROM instruction from
```
STEP 1: FROM %s AS test
```
to
```
[1/2] STEP 1/2: FROM %s AS test
```
That `[1/2]` indicates which stage we're in during a multistage build.  Opened https://github.com/openshift/origin/pull/26464, which aims to sort that out.

**Comment by nalind** [comment]
Looks we've got a test failure at https://github.com/openshift/origin/blob/134ea3ec14162a3fdd98523bf22dcbec672521f1/test/extended/builds/multistage.go#L84 caused by https://github.com/containers/buildah/pull/3265, which changed the logged output for the first FROM instruction from
```
STEP 1: FROM %s AS test
```
to
```
[1/2] STEP 1/2: FROM %s AS test
```
That `[1/2]` indicates which stage we're in during a multistage build.  Opened https://github.com/openshift/origin/pull/26464, which aims to sort that out.

**Comment by gabemontero** [comment]
@jkhelil all your failures in builds/cgroupv2/proxy are unrelated to builds

in fact, if you look at the passing tests, you'll see all the `sig-builds` tests listed in each

you are now in the mode of needing to look sippy

**Pull request merged**
