### PR TITLE
[release-4.2] update github.com/containers/storage and other dependencies

### PR DESCRIPTION
**Pull request by nalind**
Update to the latest stable release from the v1.13 branch of `github.com/containers/storage` to pick up https://github.com/containers/storage/pull/435.

Pin `github.com/openshift/library-go` to the branch for OpenShift 4.2 instead of master.

Freeze the versions of imagebuilder and source-to-image and a number of other dependencies which we don't want to update at this time.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@nalind is there a BZ for this?

**Comment by nalind** [comment]
> @nalind is there a BZ for this?

We wouldn't have gotten one for containers/storage specifically, since it only goes out as a library that's built in to other packages and not as a component on its own.

**Comment by adambkaplan** [comment]
Are the changes here similar to those in https://bugzilla.redhat.com/show_bug.cgi?id=1790525? If not then I am inclined to close this PR to reduce our backport load (especially since 4.3 is GA).

**Comment by nalind** [comment]
Tom's describing a buildah PR in that bugzilla that #127 will pull in to the release-4.3 branch; this one is mainly focused on upgrading from storage v1.13.2 to v1.13.6 to pull in https://github.com/containers/storage/pull/435.

**Comment by rhatdan** [comment]
@nalind @adambkaplan Is this still needed?

**Comment by nalind** [comment]
Going by https://access.redhat.com/support/policy/updates/openshift, it appears not.  Closing.

**Pull request closed without merging**
