### PR TITLE
Bug 1945692: move entitlement related secrets back to mounts.conf

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick of https://github.com/openshift/builder/pull/238 needed

/assign @bparees

### CODE REVIEW

**Comment by gabemontero** [comment]
hitting the `Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.` being discussed in 4-dev-triage

**Comment by gabemontero** [comment]
/hold

I'll unhold later this evening when all the AWS pruning underway finishes

**Comment by wewang58** [comment]
Today cannot install upi cluster, because of jenkins is down, will do it tomorrow

**Comment by wewang58** [comment]
Launched a upi cluster with rhel node, tested it and build complete.
/lgtm
/label qe-approved

**Pull request merged**
