### PR TITLE
Bug 1939218: bump(containers/*):

### PR DESCRIPTION
**Pull request by adambkaplan**
Bump containers/image and containers/storage to fix blobinfocache bugs
that caused builds to push image manifests that did not conform to docker
v2schema2. Removed the "replace" clause for containers/image because
buildah can support containers/image v5.10.5.

### CODE REVIEW

**Comment by nalind** [comment]
LGTM
/retest

**Comment by adambkaplan** [comment]
/hold

Needs openshift/origin#25966 to merge for build suite to pass

**Comment by gabemontero** [comment]
@adambkaplan you are also hitting 4.7 version the route name length issue with the image-eco tests.

`error: Route.route.openshift.io "nodejs-postgresql-example" is invalid: spec.host: Invalid value: "nodejs-postgresql-example-e2e-test-nodejs-postgresql-repo-test-m6qv5.apps.ci-op-13w3dbgf-5958f.origin-ci-int-aws.dev.rhcloud.com": host must conform to DNS 1123 naming conventions: [spec.host: Invalid value: "nodejs-postgresql-example-e2e-test-nodejs-postgresql-repo-test-m6qv5": must be no more than 63 characters]`

The PR I have up for that, https://github.com/openshift/origin/pull/25884 , is blocked by other unrelated failures (bz's for which I have noted in that PR).

depending on the urgency, perhaps more ci overrides in our future

**Comment by xiuwang** [comment]
Since cluster-bot doesn't work with PR, qe need to wait pr merge, then validate on nightly build.
Check the failed e2e-aws-builds job, 
There are lot of error "failed to sync configmap cache" in ci job logs, 
https://search.ci.openshift.org/?search=failed+to+sync+configmap+cache&maxAge=48h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by adambkaplan** [comment]
@vikaslaad e2e-aws-builds is in a state of perma-fail, blocked by https://github.com/openshift/origin/pull/25966

**Pull request merged**
