### PR TITLE
bump(github.com/containers/{storage,image,buildah})

### PR DESCRIPTION
**Pull request by nalind**
Bump github.com/containers/storage to v1.12.13, github.com/containers/image to v2.0.0, and github.com/containers/buildah to v1.9.1.  This brings in support for the v2 registries.conf format (https://github.com/containers/image/pull/617 and related PRs), and fixes a potential hang in chroot isolation when the child process stops reading its stdin (https://github.com/containers/buildah/pull/1668).  The updates to the storage and image libraries pull in the zstd compression library, though we don't yet support compressing image layers using it.

This pulls in more of k8s.io/api and k8s.io/apimachinery.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@nalind I would expect k8s.io bumps would be reflected in glide.lock. Did you clear the glide cache before running the bump (`glide cc`)?

**Comment by nalind** [comment]
@adambkaplan  I had not, thanks.  Refreshed it.

**Comment by adambkaplan** [comment]
/hold

will likely be replaced by #86

**Comment by nalind** [comment]
Closing since #86 was merged.

**Pull request closed without merging**
