### PR TITLE
[release-4.6] Bug 1919359: better surface dockerconfigjson errors causing image pull errors

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick cause bot failed for https://github.com/openshift/builder/pull/200#issuecomment-765507917

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by xiuwang** [comment]
/lgtm
Test on cluster building from this pr, the version '4.6.0-0.ci.test-2021-02-08-034130-ci-ln-6w1gdyt'

Could see the error from build logs with invalid pullsecret.
"error trying to parse file /var/run/secrets/openshift.io/pull/.dockerconfigjson: illegal base64 data at input byte 3"

**Pull request merged**
