### PR TITLE
Bug 1986003: Rebase to Kubernetes 1.22

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
/retest
infrastructure issue
```
 level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: Error retrieving Target Group Attributes: TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/ci-op-hnblpriv-f242d-6lbct-aext/e60484d43df1dee3' not found
level=error msg=	status code: 400, request id: 009de565-1fd9-4bd4-a38f-900cef790770
level=error
level=error msg=  on ../tmp/openshift-install-cluster-034962729/vpc/master-elb.tf line 71, in resource "aws_lb_target_group" "api_external":
level=error msg=  71: resource "aws_lb_target_group" "api_external" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change 
```

**Comment by coreydaley** [comment]
/retest
unrelated test failure/flake

**Comment by coreydaley** [comment]
/retest
infrastructure issues
```
level=error
level=error msg=Error: Error retrieving Target Group Attributes: TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/ci-op-hnblpriv-f242d-6lbct-aext/e60484d43df1dee3' not found
level=error msg=	status code: 400, request id: 009de565-1fd9-4bd4-a38f-900cef790770
level=error
level=error msg=  on ../tmp/openshift-install-cluster-034962729/vpc/master-elb.tf line 71, in resource "aws_lb_target_group" "api_external":
level=error msg=  71: resource "aws_lb_target_group" "api_external" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change 
```

**Comment by gabemontero** [comment]
well the most recent e2e-aws-image-ecosystem failure turned up an issue with the recent fix to shorten the connection timeout ... broke the retry mechanism

that fix merged 9 days ago, so it must not be frequent (I saw evidence of networking pain in various logs) but I'll be opening a new BZ for this in a few minutes and have a PR up shortly after

the cgroupsv2 e2e needs my BUILD-278 PR in this repo ... that optional job should be skipped

but I won't issue the skip yet so we can 

/test e2e-aws-image-ecosystem

/lgtm

**Comment by gabemontero** [comment]
https://github.com/openshift/cluster-samples-operator/pull/386 up for fixing retry on tbr check

**Comment by gabemontero** [comment]
the image eco suite failed, but if you look at the results, the actual tests passed, but an error occurred during must gather

/test e2e-aws-image-ecosystem

**Comment by gabemontero** [comment]
yeah that cgroupv2 won't pass until BUILD-278 merges @coreydaley 

I just wanted to see a clean image eco (that latest failures have been non samples flakes) before officially invoking a skip to clear out the cgroupv2 e2e

**Comment by gabemontero** [comment]
ok we have a green image eco

going to 

/skip 

to clear out the cgroupv2 test .... it will be covered by BUILD-278 which should cover cgroupv2 and k8s v1.22 after this PR merges.

**Comment by coreydaley** [comment]
Thanks @gabemontero 
Looks like i still need an approval from @adambkaplan

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by adambkaplan** [comment]
/label docs-approved

No documentation required for this

**Comment by adambkaplan** [comment]
/label px-approved

No PX materials required for this

**Comment by adambkaplan** [comment]
/assign @jitendar-singh 

I think the CI test for this PR is sufficient. If you agree you can label this "qe-approved" and this can merge.

**Comment by coreydaley** [comment]
/retitle Bug 1986003: Rebase to Kubernetes 1.22

**Pull request merged**
