### PR TITLE
Bug 1884270: bump(*): s2i, klog

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan

### CODE REVIEW

**Comment by gabemontero** [comment]
all green tests @adambkaplan ... changes validated 

as you mentioned in scrum, just a matter of tweaking the go.mod bump to reference an official tag

**Comment by gabemontero** [comment]
switched to the new v1.3.1 tag @adambkaplan .... PTAL

**Review by adambkaplan — APPROVED** [review]
/lgtm

Looks like the s2i bump let us drop klog v1 in the vendor dir.

**Comment by gabemontero** [comment]
> /lgtm
> 
> Looks like the s2i bump let us drop klog v1 in the vendor dir.

yes it did, and I noted klog was updated in the commit msg

**Pull request merged**
