### PR TITLE
WIP: Bug 1750650: switch git install to RH SCL to get later version supporting CA imports

### PR DESCRIPTION
**Pull request by gabemontero**
… CA import for free

/assign @bparees 
/assign @ricardomaraschini 
/assign @adambkaplan 

@openshift/openshift-team-developer-experience PTAL

with @thiagoalessio 's https://gitlab.cee.redhat.com/openshift-art/ocp-build-data/commit/077eb2ab331c5aadadd5bf6c22644533c526ae43 enabled + this PR we can obtain 2.3-5.el7

which allows us to not have to specify sslCAPath in the gitconfig file to pick up the global CA mouted cert.

obsoletes https://github.com/openshift/builder/pull/98

will mark this with https://bugzilla.redhat.com/show_bug.cgi?id=1750650 after
- ideally QE validates some of our findings on their own though if need be we won't block on this
- we have some passing tests
- we get consensus on the change

### CODE REVIEW

**Comment by gabemontero** [comment]
Installing `rh-git29` is not as seamless as we hoped @bparees : 

```
            Cloning "https://github.com/sclorg/nodejs-ex.git" ...
            error: git-remote-https: error while loading shared libraries: libcurl-httpd24.so.4: cannot open shared object file: No such file or directory
```

In the dockerfile, I just did a `ln -s`

Do I need to do an scl_enable of some sort .... I know in jenkins, our agent images have 
`ENV` with 
```
    BASH_ENV=/usr/local/bin/scl_enable \
    ENV=/usr/local/bin/scl_enable \
    PROMPT_COMMAND=". /usr/local/bin/scl_enable"
```

Perhaps I need to remove the ln -s and do the same here? .... will that automatically "update" the `git` binary?

@ricardomaraschini per our slack / bugzilla discussions, proof on my point that git uses curl libs under the covers.

**Comment by gabemontero** [comment]
The jenkins images also have this for the `scl_enable` script:

```
# This will make scl collection binaries work out of box.
unset BASH_ENV PROMPT_COMMAND ENV
source scl_source enable rh-maven35
```

assuming we would replace rh-maven35 with rh-git29

**Comment by gabemontero** [comment]
OK I've replicated the jenkins scl_enable pattern in the builder image

Let's see how the git clones in the e2e's work this time.

**Comment by gabemontero** [comment]
Hmmm ... now it is complaining about the git binary not being in the path:

```
            I0917 15:48:16.206227       1 repository.go:475] Error starting execution: exec: "git": executable file not found in $PATH
            I0917 15:48:16.206270       1 repository.go:492] Error executing command: exec: not started
            F0917 15:48:16.233252       1 helpers.go:114] error: git binary not available
```

**Comment by gabemontero** [comment]
Yeah the tests are still having difficulty using the git installed with rh-git29:

```
error: git-remote-https: error while loading shared libraries: libcurl-httpd24.so.4: cannot open shared object file: No such file or directory
```
I am out of immediate ideas.
That coupled with the difficulty in building test images with that repo is slowing things down here.

Will reset, ping  some folks who could help, tomorrow.

**Comment by adambkaplan** [comment]
@gabemontero this feels like we are entering the realm of dragons. I suspect that `git`, `libcurl`, and any other dependencies will get bumped when we use `ubi8` as the base of our images.

**Comment by gabemontero** [comment]
> @gabemontero this feels like we are entering the realm of dragons. I suspect that `git`, `libcurl`, and any other dependencies will get bumped when we use `ubi8` as the base of our images.

Yes ubi8 has already been discussed internally as a longer term solution.

I just don't think we've exhausted due diligence yet here, though I should be able to do that by today most likely.

**Comment by gabemontero** [comment]
OK with some local imagebuilder testing via http://post-office.corp.redhat.com/archives/aos-devel/2019-April/msg00376.html I've proven that the BASH / scl_enable trick does not work with the container / golang exec flow. And that the scl git is unusable without it.

After some brainstorming on slack I've got a prototype only of the first of two forms up for trying to combine scl enable and git ... certainly this is not the final form.

If either of these work, we can *entertain* the pros / cons of spending the time to productise this.  Otherwise, it is wait until the git in rhel7 is updated or we can move onto ubi8.

**Comment by gabemontero** [comment]
the first prototype generally worked .... image-eco ran clean, and e2e-aws-builds did not have the large proliferation of errors .... there were a couple of git related ones with proxy ... not sure if flakes or emblematic of something

let's get a sample of two more ... and of course the unit tests would have to be refactored

/test e2e-aws-builds

**Comment by gabemontero** [comment]
Yeah I'm still getting a few scl enable isn't happening for git operations:

```
error: git-remote-https: error while loading shared libraries: libcurl-httpd24.so.4: cannot open shared object file: No such file or directory
```

maybe there are a few more exec git paths I'm missing ... will hunt around some.

**Comment by gabemontero** [comment]
install flake e2e-aws-image-ecosystem https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_builder/99/pull-ci-openshift-builder-master-e2e-aws-image-ecosystem/263

**Comment by gabemontero** [comment]
Yeah several git operations work, and can load all the libs after scl_enable, but then `get fetch` fails and can't load the libs:

```
Sep 19 20:55:41.673: INFO: Running 'oc --namespace=e2e-test-cli-start-build-zltxb --config=/tmp/configfile527296102 logs -f build.build.openshift.io/bc-with-pr-ref-docker-1 --timestamps'
Sep 19 20:55:42.721: INFO: 2019-09-19T20:55:37.400310997Z Cloning "https://github.com/sclorg/django-ex.git" ...
2019-09-19T20:55:37.400310997Z GGM git ls-remote --heads https://github.com/sclorg/django-ex.git
2019-09-19T20:55:37.400413508Z I0919 20:55:37.400301       1 repository.go:424] GGM Executing git ls-remote --heads https://github.com/sclorg/django-ex.git
2019-09-19T20:55:37.854417626Z 090522300f6cfe9476308128684b1624e980df7b	refs/heads/master
2019-09-19T20:55:37.854417626Z e1cd63dbc34392262cf8a7b31fa08140abf69045	refs/heads/revert-40-pi-victor/upgrade_django_vers
2019-09-19T20:55:37.854417626Z 67e812ec0759d28697fbc1b80ad5a7d29ad7cb4c	refs/heads/staging
2019-09-19T20:55:37.854417626Z GGM Cloning source from https://github.com/sclorg/django-ex.git
2019-09-19T20:55:37.854417626Z I0919 20:55:37.853949       1 repository.go:424] GGM Executing git clone https://github.com/sclorg/django-ex.git /tmp/build/inputs
2019-09-19T20:55:38.239636424Z I0919 20:55:38.239585       1 repository.go:424] GGM Executing git checkout refs/pull/121/head --
2019-09-19T20:55:38.250680379Z I0919 20:55:38.250631       1 repository.go:424] GGM Executing git fetch https://github.com/sclorg/django-ex.git refs/pull/121/head
2019-09-19T20:55:38.300403769Z error: git-remote-https: error while loading shared libraries: libcurl-httpd24.so.4: cannot open shared object file: No such file or directory
```
But I can run that `git fetch` as well when I bash into the builder image with rh-git29

Might be time to punt / cry uncle and see about  either a `git` update in RHEL7 or wait until UBI8

**Comment by gabemontero** [comment]
This experiment has been noted in the Jira ticket https://jira.coreos.com/browse/DEVEXP-440 which has been filed in replacement of https://bugzilla.redhat.com/show_bug.cgi?id=1750650

**Comment by wking** [comment]
/retitle WIP: Bug 1750650: switch git install to RH SCL to get later version supporting CA imports

**Comment by gabemontero** [comment]
the failures do seem related to the use of `git` ... perhaps my tweak a couple of days ago to the bash env var in the Dockerfiles are helping

/retest

**Comment by gabemontero** [comment]
interestingly the unit tests failures around not finding `scl_source` do not show up for me locally, even though `scl_source` is not in my path

**Comment by gabemontero** [comment]
Ok the 3 failures in e2e-aws-builds were related to the new version of `git` but only in the sense that the expected messages changed slightly:

```
2020-02-06T17:34:29.27928342Z F0206 17:34:29.279232       1 helpers.go:114] error: fatal: unable to access 'https://github.com/openshift/ruby-hello-world.git/': Failed to connect to 127.0.0.1 port 3128: Connection refused
to contain substring
    <string>: unable to access 'https://github.com/openshift/ruby-hello-world.git/': Failed connect to 127.0.0.1:3128
```

```
fail [github.com/openshift/origin/test/extended/builds/cluster_config.go:327]: Expected
    <string>: Cloning "https://github.com/sclorg/nodejs-ex" ...
    GGM git ls-remote --heads https://github.com/sclorg/nodejs-ex
    I0206 17:46:26.027176       1 repository.go:424] GGM Executing git ls-remote --heads https://github.com/sclorg/nodejs-ex
    fatal: unable to access 'https://github.com/sclorg/nodejs-ex/': Could not resolve proxy: invalid.proxy.redhat.com
    error: fatal: unable to access 'https://github.com/sclorg/nodejs-ex/': Could not resolve proxy: invalid.proxy.redhat.com
to contain substring
    <string>: Could not resolve proxy: invalid.proxy.redhat.com; Unknown error
```

```
fail [github.com/openshift/origin/test/extended/builds/cluster_config.go:293]: Expected
    <string>: Cloning "https://github.com/sclorg/nodejs-ex" ...
    GGM git ls-remote --heads https://github.com/sclorg/nodejs-ex
    I0206 17:38:18.689934       1 repository.go:424] GGM Executing git ls-remote --heads https://github.com/sclorg/nodejs-ex
    fatal: unable to access 'https://github.com/sclorg/nodejs-ex/': Could not resolve proxy: invalid.proxy.redhat.com
    error: Unable to update build status: Get https://172.30.0.1:443/apis/build.openshift.io/v1/namespaces/e2e-test-build-cluster-config-2q8pn/builds/simple-s2i-build-1: proxyconnect tcp: dial tcp: lookup invalid.proxy.redhat.com on 172.30.0.10:53: no such host
    error: fatal: unable to access 'https://github.com/sclorg/nodejs-ex/': Could not resolve proxy: invalid.proxy.redhat.com
to contain substring
    <string>: Could not resolve proxy: invalid.proxy.redhat.com; Unknown error
```

No problems finding the `git` binary ... I think the flakes from last year were addressed by the Dockerfile changes.

Let's see how consistent it is.

/retest

**Comment by gabemontero** [comment]
same e2e-aws-builds results as noted in https://github.com/openshift/builder/pull/99#issuecomment-583125482

So I think we have something stable.  Just need to
- update openshift/origin e2e's to tolerate the slight modifications in error strings from the different versions of `git`
- figure out how to get the unit tests when running in prow to bypass the missing `scl_enable` issue

**Comment by gabemontero** [comment]
OK the unit tests are passing with my unit test only env var apporach for making use scl conditional

REMINDER - the change is needed in openshift/library-go (I've patched builder's vendored version for development / expediency purposes) to choose to use scl to begin with.

**Comment by gabemontero** [comment]
OK the latest e2e-aws-build correctly showed the inverse of the path for the unit tests, namely the SCL `git` was used.

**Comment by gabemontero** [comment]
The move to ubi8 and the work around for the latest rhel8 git bugs is handled by https://github.com/openshift/builder/pull/174

Presumably the same libcurl fixes around https proxy

**Pull request closed without merging**
