### PR TITLE
Bug 1872784: Bumping Buildah

### PR DESCRIPTION
**Pull request by otaviof**
Using `buildah` version `1.15.2`, given #169 is merged, we can use newest `buildah`.

### CODE REVIEW

**Comment by otaviof** [comment]
@adambkaplan, I might be late to open this PR to bump `buildah`, so please let me know. (/cc @gabemontero, @coreydaley, @nalind)

**Comment by nalind** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM
/approve

**Comment by adambkaplan** [comment]
@otaviof we need a new BZ ID if we want to merge this in 4.6. the prior BZ was related to the CVE patch in golang/x/text.

IMO it is worthwhile to add one, as each OpenShift release should incorporate the latest buildah bugfixes and enhancements.

**Comment by adambkaplan** [comment]
/hold

This actually regresses a fix in buildah - https://github.com/containers/buildah/pull/2502

**Comment by nalind** [comment]
We just tagged buildah@v1.15.2, which includes the fix we would have regressed on if we'd used v1.15.1.  @otaviof if you want to pull that in, I think we'll be okay.  Thanks!

**Comment by otaviof** [comment]
> We just tagged buildah@v1.15.2, which includes the fix we would have regressed on if we'd used v1.15.1. @otaviof if you want to pull that in, I think we'll be okay. Thanks!

Sure. Thanks for the heads up. Please consider latest changes.

**Comment by wewang58** [comment]
/bugzilla cc-qa
Add this, just test "DevExp verified bugs before PR merge" workflow.

**Comment by wewang58** [comment]
/bugzilla cc-qa
Add the label, just try to test "Bug Fix PR Pre-Merge confirmation testing" workflow

**Comment by nalind** [comment]
LGTM

**Pull request closed without merging**
