### PR TITLE
Bug 1905095: bump github.com/containers/image

### LINKED ISSUE #219: Add latest containers/image with the „quay mirror fix“
Hi,

@nalind could you please create a successor PR for https://github.com/openshift/builder/pull/213

Your PR for containers/image was successfully merged yesterday.

Thanks for all your effort and greetings,

Josef

### PR DESCRIPTION
**Pull request by nalind**
Bump github.com/containers/image from v5.5.2 to v5.10.5 to pick up https://github.com/containers/image/pull/1089 and https://github.com/containers/image/pull/1138, this pulls in an update from github.com/containers/storage from v1.24.5 to v1.24.8.
Fixes #219.

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
e2e-aws-build will fail until https://github.com/openshift/origin/pull/25949 merges

**Comment by adambkaplan** [comment]
/hold

Until ruby tests are cleaned up

**Pull request merged**
