### PR TITLE
bug 1781793: bump revert s2i bump for 1758305

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @bparees 
/assign @adambkaplan

### CODE REVIEW

**Comment by bparees** [comment]
/retitle bug 1781793: bump revert s2i bump for 1758305

**Comment by gabemontero** [comment]
install flakes

/retest

**Comment by gabemontero** [comment]
mco install flake

though based on the bugzillas noted in 4-dev-triage it might not be addressed yet

one more try just in case 

/retest

**Comment by gabemontero** [comment]
MCO pr has merged 

/retest

**Pull request merged**
