### PR TITLE
bump github.com/containers/buildah to v1.11.5

### PR DESCRIPTION
**Pull request by nalind**
Bump buildah from v1.11.4 to v1.11.5.

Also, use -mod=vendor when building in hack/build.sh, so that it won't try to update dependencies, since that's hack/update-deps.sh's job.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@nalind will this address issues identified in https://bugzilla.redhat.com/show_bug.cgi?id=1771335 - pull secrets appear to be broken in the current state.

**Comment by nalind** [comment]
@adambkaplan AFAIK it doesn't include changes that specifically address that.

**Comment by nalind** [comment]
Obsoleted by #119, closing.

**Pull request closed without merging**
