### PR TITLE
bump buildah to v1.16.7 and imagebuilder to v1.1.8

### LINKED ISSUE #219: Add latest containers/image with the „quay mirror fix“
Hi,

@nalind could you please create a successor PR for https://github.com/openshift/builder/pull/213

Your PR for containers/image was successfully merged yesterday.

Thanks for all your effort and greetings,

Josef

### PR DESCRIPTION
**Pull request by nalind**
Bump github.com/containers/buildah from v1.16.4 to v1.16.5, mainly to pick up https://github.com/containers/buildah/pull/2688, github.com/containers/storage from v1.23.3 to v1.24.0 to pick up http://github.com/containers/storage/pull/755, and github.com/openshift/imagebuilder from v1.17 to v1.18, to pick up https://github.com/openshift/imagebuilder/pull/177 and https://github.com/openshift/imagebuilder/pull/170, and github.com/containers/image/v5 from v5.5.2 to v5.10.4, to pick up https://github.com/containers/image/pull/1089 and https://github.com/containers/image/pull/1138.

Among those, imagebuilder#170, adjusts our Dockerfile parser to match quoting changes that landed in docker build 17.06, which may affect compatibility with OpenShift 3.11.

Closes #219.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
Rebased and updated to incorporate https://github.com/containers/buildah/pull/2769, https://github.com/containers/buildah/pull/2768, and https://github.com/containers/buildah/pull/2723.

/retitle bump buildah to v1.16.7 and imagebuilder to v1.1.8

**Comment by nalind** [comment]
Added a bump to github.com/containers/storage v1.24.0.

**Comment by rhatdan** [comment]
@gabemontero @coreydaley @adambkaplan @bparees @adambkaplan @smarterclayton PTAL

**Comment by nalind** [comment]
Rebased, now with an even newer version of containers/image.
/retest

**Comment by nalind** [comment]
Rebased, moved to the newest release of containers/image.

**Comment by rhatdan** [comment]
I am pretty sure this is done, should this PR be closed?

**Comment by nalind** [comment]
Yes, this is obsolete now.  Closing.

**Pull request closed without merging**
