### PR TITLE
Force use of runc, since we know we're privileged, and customize our seccomp filter

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick of @nalind 's https://github.com/openshift/builder/pull/207 required

/assign @adambkaplan 
/assign @nalind 
/assign @crawford 
/assign @jupierce 

@bparees FYI

### CODE REVIEW

**Review by adambkaplan — COMMENTED** [review]
@nalind will the seccomp profile work on a RHEL7-based container?

**Comment by nalind** [comment]
> @nalind will the seccomp profile work on a RHEL7-based container?

I think we get warnings about syscalls mentioned in the policy if they aren't recognized by the version of the libseccomp C library we link with, but that's about it.  I don't think the kernel complains if a compiled filter references a syscall number that it doesn't implement.

**Comment by gabemontero** [comment]
e2e-aws-build passed ... good news

image eco failure fix just merged recently

/retest

**Comment by gabemontero** [comment]
more lease pain with e2e-aws

/retest

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
