### PR TITLE
Bug 1754696: Bump containers/{storage,image,buildah}

### PR DESCRIPTION
**Pull request by nalind**
Bump github.com/containers/storage to v1.13.2, github.com/containers/image to v3.0.2, and github.com/containers/buildah onto its 1.8 branch, which is compatible with the others.

Bump github.com/klauspost/compress and github.com/vbauerster/mpb, as needed by the updated image library.

Bump source-to-image to its latest version, and update branches on openshift forks of packages.

Pin everything else to its previously-used version.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
We were actually using a version of source-to-image that's newer than the most recent release, so switching to pinning it to the previously-used version.

**Comment by adambkaplan** [comment]
uughh - ruby 2.2 tests are now failing. That version is EOL, will need to backport the tests in origin to fix.

**Comment by knobunc** [comment]
As the bot noted above (https://github.com/openshift/builder/pull/94#issuecomment-529506550) this will need a bug to be linked before it can be merged, along with a master branch bug that has been verified.

**Comment by adambkaplan** [comment]
/retitle Bug 1754696: Bump containers/{storage,image,buildah}

**Comment by adambkaplan** [comment]
/hold

Another PR blocked by the ruby test backport in origin

**Comment by sdodson** [comment]
@adambkaplan Is this still blocked?

**Comment by gabemontero** [comment]
those openshift/origin ext test PRs merged

**Pull request merged**
