### PR TITLE
[release-4.6] Bug 1920626: more automount of cluster trust bundle reverts; no longer automount /run/secrets

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
no sig-builds failures in e2e-aws

/retest

**Comment by gabemontero** [comment]
Forgot mounts.conf was not introduced into openshift/builder until 4.6 so no need for a 4.5 backport

**Pull request merged**
