### PR TITLE
[release-4.9] Bug 2050287: Update buildah to v1.22.4

### PR DESCRIPTION
**Pull request by adambkaplan**
Update buildah to v1.22.4 to fix bug with ADD instructions failing to
extract tar archives.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @nalind 

There was a merge conflict with the cherry pick bot, so I had to craft this manually.

**Comment by adambkaplan** [comment]
/hold

Retests cycling

**Comment by adambkaplan** [comment]
RHEL 7 test seems to remain broken, this time because the test is missing our GitHub secret for the private repo tests.

**Comment by coreydaley** [comment]
@adambkaplan Does this still need to be on hold or can it merge if the tests pass?

**Comment by coreydaley** [comment]
/label backport-risk-assessed

@jitendar-singh @Preeticp Can one of you check this out and apply the cherry-pick-approved label if applicable?

**Comment by adambkaplan** [comment]
/hold cancel

rhel7 job skipped

**Pull request merged**
