### PR TITLE
Ignore .vscode

### PR DESCRIPTION
**Pull request by adambkaplan**
/assign @gabemontero

### CODE REVIEW

**Comment by coreydaley** [comment]
Maybe just a personal preference, but .vscode should be in your .gitignore_global (since it is an editor that you use) and is not really specific to either this project, or this type of project, such as ignoring a build directory or object files, etc.

**Comment by gabemontero** [comment]
I think @coreydaley makes a good point

**Comment by coreydaley** [comment]
@bparees showed me that there is precedent in other openshift repositories for this kind of behavior, and I will go along with whatever is decided, but I do oppose it.

**Comment by bparees** [comment]
to be clear i wasn't illustrating the precedent to say "so we should do it here too.", i think @coreydaley makes a good point that there is a better solution here.  Was just observing that this PR is in good company :)

**Comment by adambkaplan** [comment]
going to update my globals now...

**Pull request closed without merging**
